-- =============================================================================
-- 004_CreateIIRComparison.sql
-- arm.usp_CompareArmToDbo - reconciles this loader's [arm] tables against the
-- incumbent [dbo] tables already in the IIR database.
--
-- GENERATED by scripts\Generate-ArmToDboComparison.ps1 against the live catalog
-- on 2026-09-28. Re-run it after a schema change rather
-- than hand-editing the pair list below.
--
-- Reports three issue kinds per table pair, plus a SUMMARY row:
--   MISSING_IN_DBO  a key present in arm but not in dbo
--   MISSING_IN_ARM  a key present in dbo but not in arm (within the window)
--   VALUE_DIFF      one row per differing COLUMN of a key-matched pair
--
-- The comparison WINDOW matters. dbo holds years of history and arm only the
-- window the loader has run for, so an unfiltered compare would report nearly
-- all of dbo as MISSING_IN_ARM. With @Date NULL the window is therefore the arm
-- table's OWN MIN..MAX of its date column; @Date narrows it to a single day.
-- Pairs with no date column (dimensions/lookups) are always compared in full.
--
-- Value columns are NOT hard-coded: they are rediscovered at run time as the
-- columns common to both tables, minus the join key, minus loader audit columns
-- (DateCreated, ModifiedAtUtc, FileLogId, RecordHash, ConduitLastUpdate), minus types that cannot be compared with <>.
-- =============================================================================

USE IIR;
GO

CREATE OR ALTER PROCEDURE arm.usp_CompareArmToDbo
    @Date            DATE    = NULL,  -- NULL = the arm table's own date range
    @TablePair       SYSNAME = NULL,  -- NULL = every pair below
    @MaxRowsPerIssue INT     = 1000   -- cap per issue kind per pair
AS
BEGIN
    SET NOCOUNT ON;

    -- Pair metadata, resolved against the live catalog at generation time.
    DECLARE @Pairs TABLE
    (
        Ord      INT IDENTITY(1,1) NOT NULL,
        ArmTable SYSNAME        NOT NULL,
        DboTable SYSNAME        NOT NULL,
        KeyJoin  NVARCHAR(1000) NOT NULL,
        KeyExprA NVARCHAR(1000) NOT NULL,
        KeyExprD NVARCHAR(1000) NOT NULL,
        DateCol  SYSNAME        NULL
    );

    INSERT @Pairs (ArmTable, DboTable, KeyJoin, KeyExprA, KeyExprD, DateCol) VALUES
        -- key RunDate + EventId; ~58 comparable value column(s)
        (N'OfflineEvent', N'OfflineEvent', N'a.[RunDate] = d.[RunDate] AND a.[EventId] = d.[EventId]', N'CONVERT(NVARCHAR(64), a.[RunDate]) + N''|'' + CONVERT(NVARCHAR(64), a.[EventId])', N'CONVERT(NVARCHAR(64), d.[RunDate]) + N''|'' + CONVERT(NVARCHAR(64), d.[EventId])', N'RunDate'),
        -- key PlantId; ~64 comparable value column(s)
        (N'Plant', N'Plant', N'a.[PlantId] = d.[PlantId]', N'CONVERT(NVARCHAR(64), a.[PlantId])', N'CONVERT(NVARCHAR(64), d.[PlantId])', N'StartupDate'),
        -- key UnitId; ~43 comparable value column(s)
        (N'Unit', N'Unit', N'a.[UnitId] = d.[UnitId]', N'CONVERT(NVARCHAR(64), a.[UnitId])', N'CONVERT(NVARCHAR(64), d.[UnitId])', N'ReleaseDate');

    -- Deliberately NOT compared:
    --   OfflineEventSummary (no dbo counterpart)
    --   PlantSummary (no dbo counterpart)
    --   UnitSummary (no dbo counterpart)

    IF @TablePair IS NOT NULL DELETE FROM @Pairs WHERE ArmTable <> @TablePair;

    CREATE TABLE #Result
    (
        Seq        INT IDENTITY(1,1) NOT NULL,
        TablePair  SYSNAME       NOT NULL,
        Issue      VARCHAR(16)   NOT NULL,
        KeyValues  NVARCHAR(512) NULL,
        ColumnName SYSNAME       NULL,
        ArmValue   NVARCHAR(256) NULL,
        DboValue   NVARCHAR(256) NULL
    );

    DECLARE @ArmTable SYSNAME, @DboTable SYSNAME, @KeyJoin NVARCHAR(1000),
            @KeyExprA NVARCHAR(1000), @KeyExprD NVARCHAR(1000), @DateCol SYSNAME,
            @sql NVARCHAR(MAX), @valueList NVARCHAR(MAX),
            @armFilter NVARCHAR(400), @dboFilter NVARCHAR(400),
            @lo DATE, @hi DATE, @armRows INT, @dboRows INT;

    DECLARE pair_cur CURSOR LOCAL FAST_FORWARD FOR
        SELECT ArmTable, DboTable, KeyJoin, KeyExprA, KeyExprD, DateCol FROM @Pairs ORDER BY Ord;
    OPEN pair_cur;
    FETCH NEXT FROM pair_cur INTO @ArmTable, @DboTable, @KeyJoin, @KeyExprA, @KeyExprD, @DateCol;

    WHILE @@FETCH_STATUS = 0
    BEGIN
        -- ---- comparison window -------------------------------------------------
        SET @lo = NULL; SET @hi = NULL;
        IF @DateCol IS NOT NULL
        BEGIN
            IF @Date IS NOT NULL
                SELECT @lo = @Date, @hi = @Date;
            ELSE
            BEGIN
                SET @sql = N'SELECT @loOut = MIN(CONVERT(DATE, ' + QUOTENAME(@DateCol) + N')),
                                    @hiOut = MAX(CONVERT(DATE, ' + QUOTENAME(@DateCol) + N'))
                             FROM arm.' + QUOTENAME(@ArmTable) + N';';
                EXEC sp_executesql @sql, N'@loOut DATE OUTPUT, @hiOut DATE OUTPUT', @loOut = @lo OUTPUT, @hiOut = @hi OUTPUT;
            END
            SET @armFilter = N'CONVERT(DATE, a.' + QUOTENAME(@DateCol) + N') BETWEEN @lo AND @hi';
            SET @dboFilter = N'CONVERT(DATE, d.' + QUOTENAME(@DateCol) + N') BETWEEN @lo AND @hi';
        END
        ELSE
        BEGIN
            SET @armFilter = N'1 = 1';
            SET @dboFilter = N'1 = 1';
        END

        -- ---- value columns common to both tables, discovered now ---------------
        SELECT @valueList = STRING_AGG(CAST(
                   N'(N' + QUOTENAME(ac.name, '''') + N', CONVERT(NVARCHAR(256), a.' + QUOTENAME(ac.name) + N')'
                 + N', CONVERT(NVARCHAR(256), d.' + QUOTENAME(ac.name) + N')'
                 + N', CASE WHEN a.' + QUOTENAME(ac.name) + N' IS NULL AND d.' + QUOTENAME(ac.name) + N' IS NULL THEN 0'
                 + N' WHEN a.' + QUOTENAME(ac.name) + N' IS NULL OR d.' + QUOTENAME(ac.name) + N' IS NULL THEN 1'
                 + N' WHEN a.' + QUOTENAME(ac.name) + N' <> d.' + QUOTENAME(ac.name) + N' THEN 1 ELSE 0 END)'
               AS NVARCHAR(MAX)), N',' + CHAR(13) + CHAR(10))
               WITHIN GROUP (ORDER BY ac.column_id)
        FROM sys.columns ac
        JOIN sys.types aty ON aty.user_type_id = ac.user_type_id
        JOIN sys.columns dc ON dc.object_id = OBJECT_ID(N'dbo.' + QUOTENAME(@DboTable)) AND dc.name = ac.name
        JOIN sys.types dty ON dty.user_type_id = dc.user_type_id
        WHERE ac.object_id = OBJECT_ID(N'arm.' + QUOTENAME(@ArmTable))
          AND ac.name NOT IN (N'DateCreated', N'ModifiedAtUtc', N'FileLogId', N'RecordHash', N'ConduitLastUpdate')
          AND aty.name NOT IN (N'geography', N'geometry', N'xml', N'image', N'text', N'ntext', N'hierarchyid', N'sql_variant', N'varbinary', N'binary', N'timestamp')
          AND dty.name NOT IN (N'geography', N'geometry', N'xml', N'image', N'text', N'ntext', N'hierarchyid', N'sql_variant', N'varbinary', N'binary', N'timestamp')
          AND CHARINDEX(N'a.' + QUOTENAME(ac.name) + N' =', @KeyJoin) = 0;   -- never diff the join key

        -- ---- rows present on one side only -------------------------------------
        SET @sql = N'
INSERT #Result (TablePair, Issue, KeyValues, ColumnName, ArmValue, DboValue)
SELECT TOP (@cap) @pair, ''MISSING_IN_DBO'', ' + @KeyExprA + N', NULL, NULL, NULL
FROM arm.' + QUOTENAME(@ArmTable) + N' a
WHERE ' + @armFilter + N'
  AND NOT EXISTS (SELECT 1 FROM dbo.' + QUOTENAME(@DboTable) + N' d WHERE ' + @KeyJoin + N');

INSERT #Result (TablePair, Issue, KeyValues, ColumnName, ArmValue, DboValue)
SELECT TOP (@cap) @pair, ''MISSING_IN_ARM'', ' + @KeyExprD + N', NULL, NULL, NULL
FROM dbo.' + QUOTENAME(@DboTable) + N' d
WHERE ' + @dboFilter + N'
  AND NOT EXISTS (SELECT 1 FROM arm.' + QUOTENAME(@ArmTable) + N' a WHERE ' + @KeyJoin + N');';

        EXEC sp_executesql @sql,
             N'@cap INT, @pair SYSNAME, @lo DATE, @hi DATE',
             @cap = @MaxRowsPerIssue, @pair = @ArmTable, @lo = @lo, @hi = @hi;

        -- ---- column-level differences on key-matched rows ----------------------
        IF @valueList IS NOT NULL
        BEGIN
            SET @sql = N'
INSERT #Result (TablePair, Issue, KeyValues, ColumnName, ArmValue, DboValue)
SELECT TOP (@cap) @pair, ''VALUE_DIFF'', ' + @KeyExprA + N', v.ColumnName, v.ArmValue, v.DboValue
FROM arm.' + QUOTENAME(@ArmTable) + N' a
JOIN dbo.' + QUOTENAME(@DboTable) + N' d ON ' + @KeyJoin + N'
CROSS APPLY (VALUES
' + @valueList + N'
) v (ColumnName, ArmValue, DboValue, IsDiff)
WHERE v.IsDiff = 1 AND ' + @armFilter + N';';

            EXEC sp_executesql @sql,
                 N'@cap INT, @pair SYSNAME, @lo DATE, @hi DATE',
                 @cap = @MaxRowsPerIssue, @pair = @ArmTable, @lo = @lo, @hi = @hi;
        END

        -- ---- per-pair summary --------------------------------------------------
        SET @sql = N'SELECT @aOut = COUNT_BIG(1) FROM arm.' + QUOTENAME(@ArmTable) + N' a WHERE ' + @armFilter + N';';
        EXEC sp_executesql @sql, N'@aOut INT OUTPUT, @lo DATE, @hi DATE', @aOut = @armRows OUTPUT, @lo = @lo, @hi = @hi;
        SET @sql = N'SELECT @dOut = COUNT_BIG(1) FROM dbo.' + QUOTENAME(@DboTable) + N' d WHERE ' + @dboFilter + N';';
        EXEC sp_executesql @sql, N'@dOut INT OUTPUT, @lo DATE, @hi DATE', @dOut = @dboRows OUTPUT, @lo = @lo, @hi = @hi;

        INSERT #Result (TablePair, Issue, KeyValues, ColumnName, ArmValue, DboValue)
        SELECT @ArmTable, 'SUMMARY',
               CASE WHEN @DateCol IS NULL THEN N'(no date column - full compare)'
                    ELSE CONCAT(@DateCol, N' ', CONVERT(NVARCHAR(10), @lo, 23), N'..', CONVERT(NVARCHAR(10), @hi, 23)) END,
               N'dbo.' + @DboTable,
               CONCAT(@armRows, N' arm row(s)'), CONCAT(@dboRows, N' dbo row(s)');

        FETCH NEXT FROM pair_cur INTO @ArmTable, @DboTable, @KeyJoin, @KeyExprA, @KeyExprD, @DateCol;
    END

    CLOSE pair_cur;
    DEALLOCATE pair_cur;

    SELECT TablePair, Issue, KeyValues, ColumnName, ArmValue, DboValue
    FROM #Result
    ORDER BY TablePair, CASE Issue WHEN 'SUMMARY' THEN 0 ELSE 1 END, Issue, Seq;
END
GO

