<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>DataLoader.Ftp</RootNamespace>
    <AssemblyName>DataLoader.Ftp</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DataLoader.Core\DataLoader.Core.csproj" />
  </ItemGroup>
</Project>
