-- =============================================================================
-- 004_CreateICEComparison.sql
-- arm.usp_CompareArmToDbo - reconciles this loader's [arm] tables against the
-- incumbent [dbo] tables already in the ICE database.
--
-- GENERATED by scripts\Generate-ArmToDboComparison.ps1 against the live catalog
-- on 2026-09-28. Re-run it after a schema change rather
-- than hand-editing the pair list below.
--
-- Reports three issue kinds per table pair, plus a SUMMARY row:
--   MISSING_IN_DBO  a key present in arm but not in dbo
--   MISSING_IN_ARM  a key present in dbo but not in arm (within the window)
--   VALUE_DIFF      one row per differing COLUMN of a key-matched pair
--
-- The comparison WINDOW matters. dbo holds years of history and arm only the
-- window the loader has run for, so an unfiltered compare would report nearly
-- all of dbo as MISSING_IN_ARM. With @Date NULL the window is therefore the arm
-- table's OWN MIN..MAX of its date column; @Date narrows it to a single day.
-- Pairs with no date column (dimensions/lookups) are always compared in full.
--
-- Value columns are NOT hard-coded: they are rediscovered at run time as the
-- columns common to both tables, minus the join key, minus loader audit columns
-- (DateCreated, ModifiedAtUtc, FileLogId, RecordHash, ConduitLastUpdate), minus types that cannot be compared with <>.
-- =============================================================================

USE ICE;
GO

CREATE OR ALTER PROCEDURE arm.usp_CompareArmToDbo
    @Date            DATE    = NULL,  -- NULL = the arm table's own date range
    @TablePair       SYSNAME = NULL,  -- NULL = every pair below
    @MaxRowsPerIssue INT     = 1000   -- cap per issue kind per pair
AS
BEGIN
    SET NOCOUNT ON;

    -- Pair metadata, resolved against the live catalog at generation time.
    DECLARE @Pairs TABLE
    (
        Ord      INT IDENTITY(1,1) NOT NULL,
        ArmTable SYSNAME        NOT NULL,
        DboTable SYSNAME        NOT NULL,
        KeyJoin  NVARCHAR(1000) NOT NULL,
        KeyExprA NVARCHAR(1000) NOT NULL,
        KeyExprD NVARCHAR(1000) NOT NULL,
        DateCol  SYSNAME        NULL
    );

    INSERT @Pairs (ArmTable, DboTable, KeyJoin, KeyExprA, KeyExprD, DateCol) VALUES
        -- key TradeDate + Contract + ContractType + Strip; ~8 comparable value column(s)
        (N'EnvFutures', N'EnvFutures', N'a.[TradeDate] = d.[TradeDate] AND a.[Contract] = d.[Contract] AND a.[ContractType] = d.[ContractType] AND a.[Strip] = d.[Strip]', N'CONVERT(NVARCHAR(64), a.[TradeDate]) + N''|'' + CONVERT(NVARCHAR(64), a.[Contract]) + N''|'' + CONVERT(NVARCHAR(64), a.[ContractType]) + N''|'' + CONVERT(NVARCHAR(64), a.[Strip])', N'CONVERT(NVARCHAR(64), d.[TradeDate]) + N''|'' + CONVERT(NVARCHAR(64), d.[Contract]) + N''|'' + CONVERT(NVARCHAR(64), d.[ContractType]) + N''|'' + CONVERT(NVARCHAR(64), d.[Strip])', N'TradeDate'),
        -- key TradeDate + Contract + ContractType + Strike + Strip; ~9 comparable value column(s)
        (N'EnvOptions', N'EnvOptions', N'a.[TradeDate] = d.[TradeDate] AND a.[Contract] = d.[Contract] AND a.[ContractType] = d.[ContractType] AND a.[Strike] = d.[Strike] AND a.[Strip] = d.[Strip]', N'CONVERT(NVARCHAR(64), a.[TradeDate]) + N''|'' + CONVERT(NVARCHAR(64), a.[Contract]) + N''|'' + CONVERT(NVARCHAR(64), a.[ContractType]) + N''|'' + CONVERT(NVARCHAR(64), a.[Strike]) + N''|'' + CONVERT(NVARCHAR(64), a.[Strip])', N'CONVERT(NVARCHAR(64), d.[TradeDate]) + N''|'' + CONVERT(NVARCHAR(64), d.[Contract]) + N''|'' + CONVERT(NVARCHAR(64), d.[ContractType]) + N''|'' + CONVERT(NVARCHAR(64), d.[Strike]) + N''|'' + CONVERT(NVARCHAR(64), d.[Strip])', N'TradeDate'),
        -- key TradeDate + Contract + ContractType + Strip + ProductId; ~7 comparable value column(s)
        (N'Futures', N'Futures', N'a.[TradeDate] = d.[TradeDate] AND a.[Contract] = d.[Contract] AND a.[ContractType] = d.[ContractType] AND a.[Strip] = d.[Strip] AND a.[ProductId] = d.[ProductId]', N'CONVERT(NVARCHAR(64), a.[TradeDate]) + N''|'' + CONVERT(NVARCHAR(64), a.[Contract]) + N''|'' + CONVERT(NVARCHAR(64), a.[ContractType]) + N''|'' + CONVERT(NVARCHAR(64), a.[Strip]) + N''|'' + CONVERT(NVARCHAR(64), a.[ProductId])', N'CONVERT(NVARCHAR(64), d.[TradeDate]) + N''|'' + CONVERT(NVARCHAR(64), d.[Contract]) + N''|'' + CONVERT(NVARCHAR(64), d.[ContractType]) + N''|'' + CONVERT(NVARCHAR(64), d.[Strip]) + N''|'' + CONVERT(NVARCHAR(64), d.[ProductId])', N'TradeDate'),
        -- key MKTID + PCC + INDEX_ID + INDEX_DATE; ~12 comparable value column(s)
        (N'ICE_Crude_Oil_Index', N'ICE_Crude_Oil_Index', N'a.[MKTID] = d.[MKTID] AND a.[PCC] = d.[PCC] AND a.[INDEX_ID] = d.[INDEX_ID] AND a.[INDEX_DATE] = d.[INDEX_DATE]', N'CONVERT(NVARCHAR(64), a.[MKTID]) + N''|'' + CONVERT(NVARCHAR(64), a.[PCC]) + N''|'' + CONVERT(NVARCHAR(64), a.[INDEX_ID]) + N''|'' + CONVERT(NVARCHAR(64), a.[INDEX_DATE])', N'CONVERT(NVARCHAR(64), d.[MKTID]) + N''|'' + CONVERT(NVARCHAR(64), d.[PCC]) + N''|'' + CONVERT(NVARCHAR(64), d.[INDEX_ID]) + N''|'' + CONVERT(NVARCHAR(64), d.[INDEX_DATE])', N'INDEX_DATE'),
        -- key TRADE_DATE + PCC_TRADE + PCC_INDEX + STRIP + INDEX_ID + DEAL_ID; ~8 comparable value column(s)
        (N'ICE_Crude_Oil_Index_Trades', N'ICE_Crude_Oil_Index_Trades', N'a.[TRADE_DATE] = d.[TRADE_DATE] AND a.[PCC_TRADE] = d.[PCC_TRADE] AND a.[PCC_INDEX] = d.[PCC_INDEX] AND a.[STRIP] = d.[STRIP] AND a.[INDEX_ID] = d.[INDEX_ID] AND a.[DEAL_ID] = d.[DEAL_ID]', N'CONVERT(NVARCHAR(64), a.[TRADE_DATE]) + N''|'' + CONVERT(NVARCHAR(64), a.[PCC_TRADE]) + N''|'' + CONVERT(NVARCHAR(64), a.[PCC_INDEX]) + N''|'' + CONVERT(NVARCHAR(64), a.[STRIP]) + N''|'' + CONVERT(NVARCHAR(64), a.[INDEX_ID]) + N''|'' + CONVERT(NVARCHAR(64), a.[DEAL_ID])', N'CONVERT(NVARCHAR(64), d.[TRADE_DATE]) + N''|'' + CONVERT(NVARCHAR(64), d.[PCC_TRADE]) + N''|'' + CONVERT(NVARCHAR(64), d.[PCC_INDEX]) + N''|'' + CONVERT(NVARCHAR(64), d.[STRIP]) + N''|'' + CONVERT(NVARCHAR(64), d.[INDEX_ID]) + N''|'' + CONVERT(NVARCHAR(64), d.[DEAL_ID])', N'TRADE_DATE'),
        -- key TradeDate + Contract + ContractType + Strip; ~8 comparable value column(s)
        (N'ICEClearedPowerFutures', N'ICEClearedPowerFutures', N'a.[TradeDate] = d.[TradeDate] AND a.[Contract] = d.[Contract] AND a.[ContractType] = d.[ContractType] AND a.[Strip] = d.[Strip]', N'CONVERT(NVARCHAR(64), a.[TradeDate]) + N''|'' + CONVERT(NVARCHAR(64), a.[Contract]) + N''|'' + CONVERT(NVARCHAR(64), a.[ContractType]) + N''|'' + CONVERT(NVARCHAR(64), a.[Strip])', N'CONVERT(NVARCHAR(64), d.[TradeDate]) + N''|'' + CONVERT(NVARCHAR(64), d.[Contract]) + N''|'' + CONVERT(NVARCHAR(64), d.[ContractType]) + N''|'' + CONVERT(NVARCHAR(64), d.[Strip])', N'TradeDate'),
        -- key TradeDate + Contract + ContractType + Strike + Strip; ~9 comparable value column(s)
        (N'ICEClearedPowerOptions', N'ICEClearedPowerOptions', N'a.[TradeDate] = d.[TradeDate] AND a.[Contract] = d.[Contract] AND a.[ContractType] = d.[ContractType] AND a.[Strike] = d.[Strike] AND a.[Strip] = d.[Strip]', N'CONVERT(NVARCHAR(64), a.[TradeDate]) + N''|'' + CONVERT(NVARCHAR(64), a.[Contract]) + N''|'' + CONVERT(NVARCHAR(64), a.[ContractType]) + N''|'' + CONVERT(NVARCHAR(64), a.[Strike]) + N''|'' + CONVERT(NVARCHAR(64), a.[Strip])', N'CONVERT(NVARCHAR(64), d.[TradeDate]) + N''|'' + CONVERT(NVARCHAR(64), d.[Contract]) + N''|'' + CONVERT(NVARCHAR(64), d.[ContractType]) + N''|'' + CONVERT(NVARCHAR(64), d.[Strike]) + N''|'' + CONVERT(NVARCHAR(64), d.[Strip])', N'TradeDate'),
        -- key TRADE_DATE + CONTRACT + STRIP + EXPIRATION_DATE + STRIKE + PUT_CALL; ~7 comparable value column(s)
        (N'ICEFCA_Options', N'ICEFCA_Options', N'a.[TRADE_DATE] = d.[TRADE_DATE] AND a.[CONTRACT] = d.[CONTRACT] AND a.[STRIP] = d.[STRIP] AND a.[EXPIRATION_DATE] = d.[EXPIRATION_DATE] AND a.[STRIKE] = d.[STRIKE] AND a.[PUT_CALL] = d.[PUT_CALL]', N'CONVERT(NVARCHAR(64), a.[TRADE_DATE]) + N''|'' + CONVERT(NVARCHAR(64), a.[CONTRACT]) + N''|'' + CONVERT(NVARCHAR(64), a.[STRIP]) + N''|'' + CONVERT(NVARCHAR(64), a.[EXPIRATION_DATE]) + N''|'' + CONVERT(NVARCHAR(64), a.[STRIKE]) + N''|'' + CONVERT(NVARCHAR(64), a.[PUT_CALL])', N'CONVERT(NVARCHAR(64), d.[TRADE_DATE]) + N''|'' + CONVERT(NVARCHAR(64), d.[CONTRACT]) + N''|'' + CONVERT(NVARCHAR(64), d.[STRIP]) + N''|'' + CONVERT(NVARCHAR(64), d.[EXPIRATION_DATE]) + N''|'' + CONVERT(NVARCHAR(64), d.[STRIKE]) + N''|'' + CONVERT(NVARCHAR(64), d.[PUT_CALL])', N'TRADE_DATE'),
        -- key TRADE_DATE + CONTRACT + STRIP + EXPIRATION_DATE + STRIKE + PUT_CALL; ~7 comparable value column(s)
        (N'ICEFUS_FinOptions', N'ICEFUS_FinOptions', N'a.[TRADE_DATE] = d.[TRADE_DATE] AND a.[CONTRACT] = d.[CONTRACT] AND a.[STRIP] = d.[STRIP] AND a.[EXPIRATION_DATE] = d.[EXPIRATION_DATE] AND a.[STRIKE] = d.[STRIKE] AND a.[PUT_CALL] = d.[PUT_CALL]', N'CONVERT(NVARCHAR(64), a.[TRADE_DATE]) + N''|'' + CONVERT(NVARCHAR(64), a.[CONTRACT]) + N''|'' + CONVERT(NVARCHAR(64), a.[STRIP]) + N''|'' + CONVERT(NVARCHAR(64), a.[EXPIRATION_DATE]) + N''|'' + CONVERT(NVARCHAR(64), a.[STRIKE]) + N''|'' + CONVERT(NVARCHAR(64), a.[PUT_CALL])', N'CONVERT(NVARCHAR(64), d.[TRADE_DATE]) + N''|'' + CONVERT(NVARCHAR(64), d.[CONTRACT]) + N''|'' + CONVERT(NVARCHAR(64), d.[STRIP]) + N''|'' + CONVERT(NVARCHAR(64), d.[EXPIRATION_DATE]) + N''|'' + CONVERT(NVARCHAR(64), d.[STRIKE]) + N''|'' + CONVERT(NVARCHAR(64), d.[PUT_CALL])', N'TRADE_DATE'),
        -- key TRADE_DATE + CONTRACT + STRIP + EXPIRATION_DATE + STRIKE + PUT_CALL; ~7 comparable value column(s)
        (N'ICEFUS_SoftOptions', N'ICEFUS_SoftOptions', N'a.[TRADE_DATE] = d.[TRADE_DATE] AND a.[CONTRACT] = d.[CONTRACT] AND a.[STRIP] = d.[STRIP] AND a.[EXPIRATION_DATE] = d.[EXPIRATION_DATE] AND a.[STRIKE] = d.[STRIKE] AND a.[PUT_CALL] = d.[PUT_CALL]', N'CONVERT(NVARCHAR(64), a.[TRADE_DATE]) + N''|'' + CONVERT(NVARCHAR(64), a.[CONTRACT]) + N''|'' + CONVERT(NVARCHAR(64), a.[STRIP]) + N''|'' + CONVERT(NVARCHAR(64), a.[EXPIRATION_DATE]) + N''|'' + CONVERT(NVARCHAR(64), a.[STRIKE]) + N''|'' + CONVERT(NVARCHAR(64), a.[PUT_CALL])', N'CONVERT(NVARCHAR(64), d.[TRADE_DATE]) + N''|'' + CONVERT(NVARCHAR(64), d.[CONTRACT]) + N''|'' + CONVERT(NVARCHAR(64), d.[STRIP]) + N''|'' + CONVERT(NVARCHAR(64), d.[EXPIRATION_DATE]) + N''|'' + CONVERT(NVARCHAR(64), d.[STRIKE]) + N''|'' + CONVERT(NVARCHAR(64), d.[PUT_CALL])', N'TRADE_DATE'),
        -- key TRADE_DATE + CONTRACT + STRIP + EXPIRATION_DATE + STRIKE + PUT_CALL; ~7 comparable value column(s)
        (N'IFLL_Options', N'IFLL_Options', N'a.[TRADE_DATE] = d.[TRADE_DATE] AND a.[CONTRACT] = d.[CONTRACT] AND a.[STRIP] = d.[STRIP] AND a.[EXPIRATION_DATE] = d.[EXPIRATION_DATE] AND a.[STRIKE] = d.[STRIKE] AND a.[PUT_CALL] = d.[PUT_CALL]', N'CONVERT(NVARCHAR(64), a.[TRADE_DATE]) + N''|'' + CONVERT(NVARCHAR(64), a.[CONTRACT]) + N''|'' + CONVERT(NVARCHAR(64), a.[STRIP]) + N''|'' + CONVERT(NVARCHAR(64), a.[EXPIRATION_DATE]) + N''|'' + CONVERT(NVARCHAR(64), a.[STRIKE]) + N''|'' + CONVERT(NVARCHAR(64), a.[PUT_CALL])', N'CONVERT(NVARCHAR(64), d.[TRADE_DATE]) + N''|'' + CONVERT(NVARCHAR(64), d.[CONTRACT]) + N''|'' + CONVERT(NVARCHAR(64), d.[STRIP]) + N''|'' + CONVERT(NVARCHAR(64), d.[EXPIRATION_DATE]) + N''|'' + CONVERT(NVARCHAR(64), d.[STRIKE]) + N''|'' + CONVERT(NVARCHAR(64), d.[PUT_CALL])', N'TRADE_DATE'),
        -- key TradeDate + Contract + ContractType + Strike + Strip; ~9 comparable value column(s)
        (N'Options', N'Options', N'a.[TradeDate] = d.[TradeDate] AND a.[Contract] = d.[Contract] AND a.[ContractType] = d.[ContractType] AND a.[Strike] = d.[Strike] AND a.[Strip] = d.[Strip]', N'CONVERT(NVARCHAR(64), a.[TradeDate]) + N''|'' + CONVERT(NVARCHAR(64), a.[Contract]) + N''|'' + CONVERT(NVARCHAR(64), a.[ContractType]) + N''|'' + CONVERT(NVARCHAR(64), a.[Strike]) + N''|'' + CONVERT(NVARCHAR(64), a.[Strip])', N'CONVERT(NVARCHAR(64), d.[TradeDate]) + N''|'' + CONVERT(NVARCHAR(64), d.[Contract]) + N''|'' + CONVERT(NVARCHAR(64), d.[ContractType]) + N''|'' + CONVERT(NVARCHAR(64), d.[Strike]) + N''|'' + CONVERT(NVARCHAR(64), d.[Strip])', N'TradeDate');

    -- Deliberately NOT compared:
    --   PhysEnvFutures (no dbo counterpart)
    --   PhysEnvOptions (no dbo counterpart)

    IF @TablePair IS NOT NULL DELETE FROM @Pairs WHERE ArmTable <> @TablePair;

    CREATE TABLE #Result
    (
        Seq        INT IDENTITY(1,1) NOT NULL,
        TablePair  SYSNAME       NOT NULL,
        Issue      VARCHAR(16)   NOT NULL,
        KeyValues  NVARCHAR(512) NULL,
        ColumnName SYSNAME       NULL,
        ArmValue   NVARCHAR(256) NULL,
        DboValue   NVARCHAR(256) NULL
    );

    DECLARE @ArmTable SYSNAME, @DboTable SYSNAME, @KeyJoin NVARCHAR(1000),
            @KeyExprA NVARCHAR(1000), @KeyExprD NVARCHAR(1000), @DateCol SYSNAME,
            @sql NVARCHAR(MAX), @valueList NVARCHAR(MAX),
            @armFilter NVARCHAR(400), @dboFilter NVARCHAR(400),
            @lo DATE, @hi DATE, @armRows INT, @dboRows INT;

    DECLARE pair_cur CURSOR LOCAL FAST_FORWARD FOR
        SELECT ArmTable, DboTable, KeyJoin, KeyExprA, KeyExprD, DateCol FROM @Pairs ORDER BY Ord;
    OPEN pair_cur;
    FETCH NEXT FROM pair_cur INTO @ArmTable, @DboTable, @KeyJoin, @KeyExprA, @KeyExprD, @DateCol;

    WHILE @@FETCH_STATUS = 0
    BEGIN
        -- ---- comparison window -------------------------------------------------
        SET @lo = NULL; SET @hi = NULL;
        IF @DateCol IS NOT NULL
        BEGIN
            IF @Date IS NOT NULL
                SELECT @lo = @Date, @hi = @Date;
            ELSE
            BEGIN
                SET @sql = N'SELECT @loOut = MIN(CONVERT(DATE, ' + QUOTENAME(@DateCol) + N')),
                                    @hiOut = MAX(CONVERT(DATE, ' + QUOTENAME(@DateCol) + N'))
                             FROM arm.' + QUOTENAME(@ArmTable) + N';';
                EXEC sp_executesql @sql, N'@loOut DATE OUTPUT, @hiOut DATE OUTPUT', @loOut = @lo OUTPUT, @hiOut = @hi OUTPUT;
            END
            SET @armFilter = N'CONVERT(DATE, a.' + QUOTENAME(@DateCol) + N') BETWEEN @lo AND @hi';
            SET @dboFilter = N'CONVERT(DATE, d.' + QUOTENAME(@DateCol) + N') BETWEEN @lo AND @hi';
        END
        ELSE
        BEGIN
            SET @armFilter = N'1 = 1';
            SET @dboFilter = N'1 = 1';
        END

        -- ---- value columns common to both tables, discovered now ---------------
        SELECT @valueList = STRING_AGG(CAST(
                   N'(N' + QUOTENAME(ac.name, '''') + N', CONVERT(NVARCHAR(256), a.' + QUOTENAME(ac.name) + N')'
                 + N', CONVERT(NVARCHAR(256), d.' + QUOTENAME(ac.name) + N')'
                 + N', CASE WHEN a.' + QUOTENAME(ac.name) + N' IS NULL AND d.' + QUOTENAME(ac.name) + N' IS NULL THEN 0'
                 + N' WHEN a.' + QUOTENAME(ac.name) + N' IS NULL OR d.' + QUOTENAME(ac.name) + N' IS NULL THEN 1'
                 + N' WHEN a.' + QUOTENAME(ac.name) + N' <> d.' + QUOTENAME(ac.name) + N' THEN 1 ELSE 0 END)'
               AS NVARCHAR(MAX)), N',' + CHAR(13) + CHAR(10))
               WITHIN GROUP (ORDER BY ac.column_id)
        FROM sys.columns ac
        JOIN sys.types aty ON aty.user_type_id = ac.user_type_id
        JOIN sys.columns dc ON dc.object_id = OBJECT_ID(N'dbo.' + QUOTENAME(@DboTable)) AND dc.name = ac.name
        JOIN sys.types dty ON dty.user_type_id = dc.user_type_id
        WHERE ac.object_id = OBJECT_ID(N'arm.' + QUOTENAME(@ArmTable))
          AND ac.name NOT IN (N'DateCreated', N'ModifiedAtUtc', N'FileLogId', N'RecordHash', N'ConduitLastUpdate')
          AND aty.name NOT IN (N'geography', N'geometry', N'xml', N'image', N'text', N'ntext', N'hierarchyid', N'sql_variant', N'varbinary', N'binary', N'timestamp')
          AND dty.name NOT IN (N'geography', N'geometry', N'xml', N'image', N'text', N'ntext', N'hierarchyid', N'sql_variant', N'varbinary', N'binary', N'timestamp')
          AND CHARINDEX(N'a.' + QUOTENAME(ac.name) + N' =', @KeyJoin) = 0;   -- never diff the join key

        -- ---- rows present on one side only -------------------------------------
        SET @sql = N'
INSERT #Result (TablePair, Issue, KeyValues, ColumnName, ArmValue, DboValue)
SELECT TOP (@cap) @pair, ''MISSING_IN_DBO'', ' + @KeyExprA + N', NULL, NULL, NULL
FROM arm.' + QUOTENAME(@ArmTable) + N' a
WHERE ' + @armFilter + N'
  AND NOT EXISTS (SELECT 1 FROM dbo.' + QUOTENAME(@DboTable) + N' d WHERE ' + @KeyJoin + N');

INSERT #Result (TablePair, Issue, KeyValues, ColumnName, ArmValue, DboValue)
SELECT TOP (@cap) @pair, ''MISSING_IN_ARM'', ' + @KeyExprD + N', NULL, NULL, NULL
FROM dbo.' + QUOTENAME(@DboTable) + N' d
WHERE ' + @dboFilter + N'
  AND NOT EXISTS (SELECT 1 FROM arm.' + QUOTENAME(@ArmTable) + N' a WHERE ' + @KeyJoin + N');';

        EXEC sp_executesql @sql,
             N'@cap INT, @pair SYSNAME, @lo DATE, @hi DATE',
             @cap = @MaxRowsPerIssue, @pair = @ArmTable, @lo = @lo, @hi = @hi;

        -- ---- column-level differences on key-matched rows ----------------------
        IF @valueList IS NOT NULL
        BEGIN
            SET @sql = N'
INSERT #Result (TablePair, Issue, KeyValues, ColumnName, ArmValue, DboValue)
SELECT TOP (@cap) @pair, ''VALUE_DIFF'', ' + @KeyExprA + N', v.ColumnName, v.ArmValue, v.DboValue
FROM arm.' + QUOTENAME(@ArmTable) + N' a
JOIN dbo.' + QUOTENAME(@DboTable) + N' d ON ' + @KeyJoin + N'
CROSS APPLY (VALUES
' + @valueList + N'
) v (ColumnName, ArmValue, DboValue, IsDiff)
WHERE v.IsDiff = 1 AND ' + @armFilter + N';';

            EXEC sp_executesql @sql,
                 N'@cap INT, @pair SYSNAME, @lo DATE, @hi DATE',
                 @cap = @MaxRowsPerIssue, @pair = @ArmTable, @lo = @lo, @hi = @hi;
        END

        -- ---- per-pair summary --------------------------------------------------
        SET @sql = N'SELECT @aOut = COUNT_BIG(1) FROM arm.' + QUOTENAME(@ArmTable) + N' a WHERE ' + @armFilter + N';';
        EXEC sp_executesql @sql, N'@aOut INT OUTPUT, @lo DATE, @hi DATE', @aOut = @armRows OUTPUT, @lo = @lo, @hi = @hi;
        SET @sql = N'SELECT @dOut = COUNT_BIG(1) FROM dbo.' + QUOTENAME(@DboTable) + N' d WHERE ' + @dboFilter + N';';
        EXEC sp_executesql @sql, N'@dOut INT OUTPUT, @lo DATE, @hi DATE', @dOut = @dboRows OUTPUT, @lo = @lo, @hi = @hi;

        INSERT #Result (TablePair, Issue, KeyValues, ColumnName, ArmValue, DboValue)
        SELECT @ArmTable, 'SUMMARY',
               CASE WHEN @DateCol IS NULL THEN N'(no date column - full compare)'
                    ELSE CONCAT(@DateCol, N' ', CONVERT(NVARCHAR(10), @lo, 23), N'..', CONVERT(NVARCHAR(10), @hi, 23)) END,
               N'dbo.' + @DboTable,
               CONCAT(@armRows, N' arm row(s)'), CONCAT(@dboRows, N' dbo row(s)');

        FETCH NEXT FROM pair_cur INTO @ArmTable, @DboTable, @KeyJoin, @KeyExprA, @KeyExprD, @DateCol;
    END

    CLOSE pair_cur;
    DEALLOCATE pair_cur;

    SELECT TablePair, Issue, KeyValues, ColumnName, ArmValue, DboValue
    FROM #Result
    ORDER BY TablePair, CASE Issue WHEN 'SUMMARY' THEN 0 ELSE 1 END, Issue, Seq;
END
GO

