-- =============================================================================
-- 004_CreateIHSPointLogicComparison.sql
-- arm.usp_CompareArmToDbo - reconciles this loader's [arm] tables against the
-- incumbent [dbo] tables already in the IHSPointLogic database.
--
-- GENERATED by scripts\Generate-ArmToDboComparison.ps1 against the live catalog
-- on 2026-09-28. Re-run it after a schema change rather
-- than hand-editing the pair list below.
--
-- Reports three issue kinds per table pair, plus a SUMMARY row:
--   MISSING_IN_DBO  a key present in arm but not in dbo
--   MISSING_IN_ARM  a key present in dbo but not in arm (within the window)
--   VALUE_DIFF      one row per differing COLUMN of a key-matched pair
--
-- The comparison WINDOW matters. dbo holds years of history and arm only the
-- window the loader has run for, so an unfiltered compare would report nearly
-- all of dbo as MISSING_IN_ARM. With @Date NULL the window is therefore the arm
-- table's OWN MIN..MAX of its date column; @Date narrows it to a single day.
-- Pairs with no date column (dimensions/lookups) are always compared in full.
--
-- Value columns are NOT hard-coded: they are rediscovered at run time as the
-- columns common to both tables, minus the join key, minus loader audit columns
-- (DateCreated, ModifiedAtUtc, FileLogId, RecordHash, ConduitLastUpdate), minus types that cannot be compared with <>.
-- =============================================================================

USE IHSPointLogic;
GO

CREATE OR ALTER PROCEDURE arm.usp_CompareArmToDbo
    @Date            DATE    = NULL,  -- NULL = the arm table's own date range
    @TablePair       SYSNAME = NULL,  -- NULL = every pair below
    @MaxRowsPerIssue INT     = 1000   -- cap per issue kind per pair
AS
BEGIN
    SET NOCOUNT ON;

    -- Pair metadata, resolved against the live catalog at generation time.
    DECLARE @Pairs TABLE
    (
        Ord      INT IDENTITY(1,1) NOT NULL,
        ArmTable SYSNAME        NOT NULL,
        DboTable SYSNAME        NOT NULL,
        KeyJoin  NVARCHAR(1000) NOT NULL,
        KeyExprA NVARCHAR(1000) NOT NULL,
        KeyExprD NVARCHAR(1000) NOT NULL,
        DateCol  SYSNAME        NULL
    );

    INSERT @Pairs (ArmTable, DboTable, KeyJoin, KeyExprA, KeyExprD, DateCol) VALUES
        -- key CountyId + StateId; ~0 comparable value column(s); no date column - always compared in full
        (N'County', N'County', N'a.[CountyId] = d.[CountyId] AND a.[StateId] = d.[StateId]', N'CONVERT(NVARCHAR(64), a.[CountyId]) + N''|'' + CONVERT(NVARCHAR(64), a.[StateId])', N'CONVERT(NVARCHAR(64), d.[CountyId]) + N''|'' + CONVERT(NVARCHAR(64), d.[StateId])', NULL),
        -- key ForecastDate + Date + Region + Subregion; ~5 comparable value column(s)
        (N'DemandForecastRegion', N'DemandForecastRegion', N'a.[ForecastDate] = d.[ForecastDate] AND a.[Date] = d.[Date] AND a.[Region] = d.[Region] AND a.[Subregion] = d.[Subregion]', N'CONVERT(NVARCHAR(64), a.[ForecastDate]) + N''|'' + CONVERT(NVARCHAR(64), a.[Date]) + N''|'' + CONVERT(NVARCHAR(64), a.[Region]) + N''|'' + CONVERT(NVARCHAR(64), a.[Subregion])', N'CONVERT(NVARCHAR(64), d.[ForecastDate]) + N''|'' + CONVERT(NVARCHAR(64), d.[Date]) + N''|'' + CONVERT(NVARCHAR(64), d.[Region]) + N''|'' + CONVERT(NVARCHAR(64), d.[Subregion])', N'ForecastDate'),
        -- key ForecastDate + Date + Region; ~3 comparable value column(s)
        (N'DemandForecastUsLower48', N'DemandForecastUSLower48', N'a.[ForecastDate] = d.[ForecastDate] AND a.[Date] = d.[Date] AND a.[Region] = d.[Region]', N'CONVERT(NVARCHAR(64), a.[ForecastDate]) + N''|'' + CONVERT(NVARCHAR(64), a.[Date]) + N''|'' + CONVERT(NVARCHAR(64), a.[Region])', N'CONVERT(NVARCHAR(64), d.[ForecastDate]) + N''|'' + CONVERT(NVARCHAR(64), d.[Date]) + N''|'' + CONVERT(NVARCHAR(64), d.[Region])', N'ForecastDate'),
        -- key FacilityId + PointTypeId; ~0 comparable value column(s); no date column - always compared in full
        (N'Facility', N'Facility', N'a.[FacilityId] = d.[FacilityId] AND a.[PointTypeId] = d.[PointTypeId]', N'CONVERT(NVARCHAR(64), a.[FacilityId]) + N''|'' + CONVERT(NVARCHAR(64), a.[PointTypeId])', N'CONVERT(NVARCHAR(64), d.[FacilityId]) + N''|'' + CONVERT(NVARCHAR(64), d.[PointTypeId])', NULL),
        -- key ReportedDate + ReferenceDate + Region + ProducingArea + State; ~2 comparable value column(s)
        (N'GasProductionProducingArea', N'GasProduction_ProducingArea', N'a.[ReportedDate] = d.[ReportedDate] AND a.[ReferenceDate] = d.[ReferenceDate] AND a.[Region] = d.[Region] AND a.[ProducingArea] = d.[ProducingArea] AND a.[State] = d.[State]', N'CONVERT(NVARCHAR(64), a.[ReportedDate]) + N''|'' + CONVERT(NVARCHAR(64), a.[ReferenceDate]) + N''|'' + CONVERT(NVARCHAR(64), a.[Region]) + N''|'' + CONVERT(NVARCHAR(64), a.[ProducingArea]) + N''|'' + CONVERT(NVARCHAR(64), a.[State])', N'CONVERT(NVARCHAR(64), d.[ReportedDate]) + N''|'' + CONVERT(NVARCHAR(64), d.[ReferenceDate]) + N''|'' + CONVERT(NVARCHAR(64), d.[Region]) + N''|'' + CONVERT(NVARCHAR(64), d.[ProducingArea]) + N''|'' + CONVERT(NVARCHAR(64), d.[State])', N'ReportedDate'),
        -- key TimePeriod; ~16 comparable value column(s)
        (N'MarketBalancesUsLower48', N'MarketBalancesUSLower48', N'a.[TimePeriod] = d.[TimePeriod]', N'CONVERT(NVARCHAR(64), a.[TimePeriod])', N'CONVERT(NVARCHAR(64), d.[TimePeriod])', N'TimePeriod'),
        -- key ReferenceDate + PLEProductName + RegionName; ~1 comparable value column(s)
        (N'ModeledDemandRegionType', N'ModeledDemandRegionType', N'a.[ReferenceDate] = d.[ReferenceDate] AND a.[PLEProductName] = d.[PLEProductName] AND a.[RegionName] = d.[RegionName]', N'CONVERT(NVARCHAR(64), a.[ReferenceDate]) + N''|'' + CONVERT(NVARCHAR(64), a.[PLEProductName]) + N''|'' + CONVERT(NVARCHAR(64), a.[RegionName])', N'CONVERT(NVARCHAR(64), d.[ReferenceDate]) + N''|'' + CONVERT(NVARCHAR(64), d.[PLEProductName]) + N''|'' + CONVERT(NVARCHAR(64), d.[RegionName])', N'ReferenceDate'),
        -- key PipelineId; ~0 comparable value column(s); no date column - always compared in full
        (N'Pipeline', N'Pipeline', N'a.[PipelineId] = d.[PipelineId]', N'CONVERT(NVARCHAR(64), a.[PipelineId])', N'CONVERT(NVARCHAR(64), d.[PipelineId])', NULL),
        -- key FlowDate + Region + Pipeline + Throughput + FlowType; ~1 comparable value column(s)
        (N'PipelineFlowThroughput', N'PipelineFlowThroughput', N'a.[FlowDate] = d.[FlowDate] AND a.[Region] = d.[Region] AND a.[Pipeline] = d.[Pipeline] AND a.[Throughput] = d.[Throughput] AND a.[FlowType] = d.[FlowType]', N'CONVERT(NVARCHAR(64), a.[FlowDate]) + N''|'' + CONVERT(NVARCHAR(64), a.[Region]) + N''|'' + CONVERT(NVARCHAR(64), a.[Pipeline]) + N''|'' + CONVERT(NVARCHAR(64), a.[Throughput]) + N''|'' + CONVERT(NVARCHAR(64), a.[FlowType])', N'CONVERT(NVARCHAR(64), d.[FlowDate]) + N''|'' + CONVERT(NVARCHAR(64), d.[Region]) + N''|'' + CONVERT(NVARCHAR(64), d.[Pipeline]) + N''|'' + CONVERT(NVARCHAR(64), d.[Throughput]) + N''|'' + CONVERT(NVARCHAR(64), d.[FlowType])', N'FlowDate'),
        -- key PipelineNoticeCategoryId; ~0 comparable value column(s); no date column - always compared in full
        (N'PipelineNoticeCategory', N'PipelineNoticeCategory', N'a.[PipelineNoticeCategoryId] = d.[PipelineNoticeCategoryId]', N'CONVERT(NVARCHAR(64), a.[PipelineNoticeCategoryId])', N'CONVERT(NVARCHAR(64), d.[PipelineNoticeCategoryId])', NULL),
        -- key Id; ~10 comparable value column(s)
        (N'PipelineNoticeSearch', N'PipelineNoticeSearch', N'a.[Id] = d.[Id]', N'CONVERT(NVARCHAR(64), a.[Id])', N'CONVERT(NVARCHAR(64), d.[Id])', N'PostedDate'),
        -- key PointId; ~3 comparable value column(s); no date column - always compared in full
        (N'Point', N'Point', N'a.[PointId] = d.[PointId]', N'CONVERT(NVARCHAR(64), a.[PointId])', N'CONVERT(NVARCHAR(64), d.[PointId])', NULL),
        -- key PointId; ~21 comparable value column(s); no date column - always compared in full
        (N'PointMetadata', N'PointMetadata', N'a.[PointId] = d.[PointId]', N'CONVERT(NVARCHAR(64), a.[PointId])', N'CONVERT(NVARCHAR(64), d.[PointId])', NULL),
        -- key PointStatusId; ~0 comparable value column(s); no date column - always compared in full
        (N'PointStatus', N'PointStatus', N'a.[PointStatusId] = d.[PointStatusId]', N'CONVERT(NVARCHAR(64), a.[PointStatusId])', N'CONVERT(NVARCHAR(64), d.[PointStatusId])', NULL),
        -- key PointTypeId; ~0 comparable value column(s); no date column - always compared in full
        (N'PointType', N'PointType', N'a.[PointTypeId] = d.[PointTypeId]', N'CONVERT(NVARCHAR(64), a.[PointTypeId])', N'CONVERT(NVARCHAR(64), d.[PointTypeId])', NULL),
        -- key PointId + Date; ~1 comparable value column(s)
        (N'PointVolume', N'PointVolume', N'a.[PointId] = d.[PointId] AND a.[Date] = d.[Date]', N'CONVERT(NVARCHAR(64), a.[PointId]) + N''|'' + CONVERT(NVARCHAR(64), a.[Date])', N'CONVERT(NVARCHAR(64), d.[PointId]) + N''|'' + CONVERT(NVARCHAR(64), d.[Date])', N'Date'),
        -- key StateId; ~0 comparable value column(s); no date column - always compared in full
        (N'State', N'State', N'a.[StateId] = d.[StateId]', N'CONVERT(NVARCHAR(64), a.[StateId])', N'CONVERT(NVARCHAR(64), d.[StateId])', NULL),
        -- key FlowDate + Region + FromState + ToState + FlowType; ~1 comparable value column(s)
        (N'StateFlowsThroughputAggregate', N'StateFlowsThroughputAggregate', N'a.[FlowDate] = d.[FlowDate] AND a.[Region] = d.[Region] AND a.[FromState] = d.[FromState] AND a.[ToState] = d.[ToState] AND a.[FlowType] = d.[FlowType]', N'CONVERT(NVARCHAR(64), a.[FlowDate]) + N''|'' + CONVERT(NVARCHAR(64), a.[Region]) + N''|'' + CONVERT(NVARCHAR(64), a.[FromState]) + N''|'' + CONVERT(NVARCHAR(64), a.[ToState]) + N''|'' + CONVERT(NVARCHAR(64), a.[FlowType])', N'CONVERT(NVARCHAR(64), d.[FlowDate]) + N''|'' + CONVERT(NVARCHAR(64), d.[Region]) + N''|'' + CONVERT(NVARCHAR(64), d.[FromState]) + N''|'' + CONVERT(NVARCHAR(64), d.[ToState]) + N''|'' + CONVERT(NVARCHAR(64), d.[FlowType])', N'FlowDate'),
        -- key SubRegionId + RegionId; ~0 comparable value column(s); no date column - always compared in full
        (N'Subregion', N'SubRegion', N'a.[SubRegionId] = d.[SubRegionId] AND a.[RegionId] = d.[RegionId]', N'CONVERT(NVARCHAR(64), a.[SubRegionId]) + N''|'' + CONVERT(NVARCHAR(64), a.[RegionId])', N'CONVERT(NVARCHAR(64), d.[SubRegionId]) + N''|'' + CONVERT(NVARCHAR(64), d.[RegionId])', NULL),
        -- key Date; ~16 comparable value column(s)
        (N'SupplyAndDemand', N'SupplyAndDemand', N'a.[Date] = d.[Date]', N'CONVERT(NVARCHAR(64), a.[Date])', N'CONVERT(NVARCHAR(64), d.[Date])', N'Date'),
        -- key RegionId + Date + Product; ~0 comparable value column(s)
        (N'SupplyAndDemandByRegion', N'SupplyAndDemandByRegion', N'a.[RegionId] = d.[RegionId] AND a.[Date] = d.[Date] AND a.[Product] = d.[Product]', N'CONVERT(NVARCHAR(64), a.[RegionId]) + N''|'' + CONVERT(NVARCHAR(64), a.[Date]) + N''|'' + CONVERT(NVARCHAR(64), a.[Product])', N'CONVERT(NVARCHAR(64), d.[RegionId]) + N''|'' + CONVERT(NVARCHAR(64), d.[Date]) + N''|'' + CONVERT(NVARCHAR(64), d.[Product])', N'Date'),
        -- key SubRegionId + RegionId + Date + Product; ~0 comparable value column(s)
        (N'SupplyAndDemandBySubRegion', N'SupplyAndDemandBySubRegion', N'a.[SubRegionId] = d.[SubRegionId] AND a.[RegionId] = d.[RegionId] AND a.[Date] = d.[Date] AND a.[Product] = d.[Product]', N'CONVERT(NVARCHAR(64), a.[SubRegionId]) + N''|'' + CONVERT(NVARCHAR(64), a.[RegionId]) + N''|'' + CONVERT(NVARCHAR(64), a.[Date]) + N''|'' + CONVERT(NVARCHAR(64), a.[Product])', N'CONVERT(NVARCHAR(64), d.[SubRegionId]) + N''|'' + CONVERT(NVARCHAR(64), d.[RegionId]) + N''|'' + CONVERT(NVARCHAR(64), d.[Date]) + N''|'' + CONVERT(NVARCHAR(64), d.[Product])', N'Date'),
        -- key RunDate + FlowDate + PointName + PipelineName + LedgerSide; ~6 comparable value column(s)
        (N'UsImportsExportsByPointsAggregate', N'USImportsExportsByPointsAggregate', N'a.[RunDate] = d.[RunDate] AND a.[FlowDate] = d.[FlowDate] AND a.[PointName] = d.[PointName] AND a.[PipelineName] = d.[PipelineName] AND a.[LedgerSide] = d.[LedgerSide]', N'CONVERT(NVARCHAR(64), a.[RunDate]) + N''|'' + CONVERT(NVARCHAR(64), a.[FlowDate]) + N''|'' + CONVERT(NVARCHAR(64), a.[PointName]) + N''|'' + CONVERT(NVARCHAR(64), a.[PipelineName]) + N''|'' + CONVERT(NVARCHAR(64), a.[LedgerSide])', N'CONVERT(NVARCHAR(64), d.[RunDate]) + N''|'' + CONVERT(NVARCHAR(64), d.[FlowDate]) + N''|'' + CONVERT(NVARCHAR(64), d.[PointName]) + N''|'' + CONVERT(NVARCHAR(64), d.[PipelineName]) + N''|'' + CONVERT(NVARCHAR(64), d.[LedgerSide])', N'RunDate'),
        -- key ReportDate + FlowDate + Name + EiaRegion + State + FieldType; ~1 comparable value column(s)
        (N'UsSampleStorageFacility', N'US_SampleStorage_Facility', N'a.[ReportDate] = d.[ReportDate] AND a.[FlowDate] = d.[FlowDate] AND a.[Name] = d.[Name] AND a.[EiaRegion] = d.[EiaRegion] AND a.[State] = d.[State] AND a.[FieldType] = d.[FieldType]', N'CONVERT(NVARCHAR(64), a.[ReportDate]) + N''|'' + CONVERT(NVARCHAR(64), a.[FlowDate]) + N''|'' + CONVERT(NVARCHAR(64), a.[Name]) + N''|'' + CONVERT(NVARCHAR(64), a.[EiaRegion]) + N''|'' + CONVERT(NVARCHAR(64), a.[State]) + N''|'' + CONVERT(NVARCHAR(64), a.[FieldType])', N'CONVERT(NVARCHAR(64), d.[ReportDate]) + N''|'' + CONVERT(NVARCHAR(64), d.[FlowDate]) + N''|'' + CONVERT(NVARCHAR(64), d.[Name]) + N''|'' + CONVERT(NVARCHAR(64), d.[EiaRegion]) + N''|'' + CONVERT(NVARCHAR(64), d.[State]) + N''|'' + CONVERT(NVARCHAR(64), d.[FieldType])', N'ReportDate');

    IF @TablePair IS NOT NULL DELETE FROM @Pairs WHERE ArmTable <> @TablePair;

    CREATE TABLE #Result
    (
        Seq        INT IDENTITY(1,1) NOT NULL,
        TablePair  SYSNAME       NOT NULL,
        Issue      VARCHAR(16)   NOT NULL,
        KeyValues  NVARCHAR(512) NULL,
        ColumnName SYSNAME       NULL,
        ArmValue   NVARCHAR(256) NULL,
        DboValue   NVARCHAR(256) NULL
    );

    DECLARE @ArmTable SYSNAME, @DboTable SYSNAME, @KeyJoin NVARCHAR(1000),
            @KeyExprA NVARCHAR(1000), @KeyExprD NVARCHAR(1000), @DateCol SYSNAME,
            @sql NVARCHAR(MAX), @valueList NVARCHAR(MAX),
            @armFilter NVARCHAR(400), @dboFilter NVARCHAR(400),
            @lo DATE, @hi DATE, @armRows INT, @dboRows INT;

    DECLARE pair_cur CURSOR LOCAL FAST_FORWARD FOR
        SELECT ArmTable, DboTable, KeyJoin, KeyExprA, KeyExprD, DateCol FROM @Pairs ORDER BY Ord;
    OPEN pair_cur;
    FETCH NEXT FROM pair_cur INTO @ArmTable, @DboTable, @KeyJoin, @KeyExprA, @KeyExprD, @DateCol;

    WHILE @@FETCH_STATUS = 0
    BEGIN
        -- ---- comparison window -------------------------------------------------
        SET @lo = NULL; SET @hi = NULL;
        IF @DateCol IS NOT NULL
        BEGIN
            IF @Date IS NOT NULL
                SELECT @lo = @Date, @hi = @Date;
            ELSE
            BEGIN
                SET @sql = N'SELECT @loOut = MIN(CONVERT(DATE, ' + QUOTENAME(@DateCol) + N')),
                                    @hiOut = MAX(CONVERT(DATE, ' + QUOTENAME(@DateCol) + N'))
                             FROM arm.' + QUOTENAME(@ArmTable) + N';';
                EXEC sp_executesql @sql, N'@loOut DATE OUTPUT, @hiOut DATE OUTPUT', @loOut = @lo OUTPUT, @hiOut = @hi OUTPUT;
            END
            SET @armFilter = N'CONVERT(DATE, a.' + QUOTENAME(@DateCol) + N') BETWEEN @lo AND @hi';
            SET @dboFilter = N'CONVERT(DATE, d.' + QUOTENAME(@DateCol) + N') BETWEEN @lo AND @hi';
        END
        ELSE
        BEGIN
            SET @armFilter = N'1 = 1';
            SET @dboFilter = N'1 = 1';
        END

        -- ---- value columns common to both tables, discovered now ---------------
        SELECT @valueList = STRING_AGG(CAST(
                   N'(N' + QUOTENAME(ac.name, '''') + N', CONVERT(NVARCHAR(256), a.' + QUOTENAME(ac.name) + N')'
                 + N', CONVERT(NVARCHAR(256), d.' + QUOTENAME(ac.name) + N')'
                 + N', CASE WHEN a.' + QUOTENAME(ac.name) + N' IS NULL AND d.' + QUOTENAME(ac.name) + N' IS NULL THEN 0'
                 + N' WHEN a.' + QUOTENAME(ac.name) + N' IS NULL OR d.' + QUOTENAME(ac.name) + N' IS NULL THEN 1'
                 + N' WHEN a.' + QUOTENAME(ac.name) + N' <> d.' + QUOTENAME(ac.name) + N' THEN 1 ELSE 0 END)'
               AS NVARCHAR(MAX)), N',' + CHAR(13) + CHAR(10))
               WITHIN GROUP (ORDER BY ac.column_id)
        FROM sys.columns ac
        JOIN sys.types aty ON aty.user_type_id = ac.user_type_id
        JOIN sys.columns dc ON dc.object_id = OBJECT_ID(N'dbo.' + QUOTENAME(@DboTable)) AND dc.name = ac.name
        JOIN sys.types dty ON dty.user_type_id = dc.user_type_id
        WHERE ac.object_id = OBJECT_ID(N'arm.' + QUOTENAME(@ArmTable))
          AND ac.name NOT IN (N'DateCreated', N'ModifiedAtUtc', N'FileLogId', N'RecordHash', N'ConduitLastUpdate')
          AND aty.name NOT IN (N'geography', N'geometry', N'xml', N'image', N'text', N'ntext', N'hierarchyid', N'sql_variant', N'varbinary', N'binary', N'timestamp')
          AND dty.name NOT IN (N'geography', N'geometry', N'xml', N'image', N'text', N'ntext', N'hierarchyid', N'sql_variant', N'varbinary', N'binary', N'timestamp')
          AND CHARINDEX(N'a.' + QUOTENAME(ac.name) + N' =', @KeyJoin) = 0;   -- never diff the join key

        -- ---- rows present on one side only -------------------------------------
        SET @sql = N'
INSERT #Result (TablePair, Issue, KeyValues, ColumnName, ArmValue, DboValue)
SELECT TOP (@cap) @pair, ''MISSING_IN_DBO'', ' + @KeyExprA + N', NULL, NULL, NULL
FROM arm.' + QUOTENAME(@ArmTable) + N' a
WHERE ' + @armFilter + N'
  AND NOT EXISTS (SELECT 1 FROM dbo.' + QUOTENAME(@DboTable) + N' d WHERE ' + @KeyJoin + N');

INSERT #Result (TablePair, Issue, KeyValues, ColumnName, ArmValue, DboValue)
SELECT TOP (@cap) @pair, ''MISSING_IN_ARM'', ' + @KeyExprD + N', NULL, NULL, NULL
FROM dbo.' + QUOTENAME(@DboTable) + N' d
WHERE ' + @dboFilter + N'
  AND NOT EXISTS (SELECT 1 FROM arm.' + QUOTENAME(@ArmTable) + N' a WHERE ' + @KeyJoin + N');';

        EXEC sp_executesql @sql,
             N'@cap INT, @pair SYSNAME, @lo DATE, @hi DATE',
             @cap = @MaxRowsPerIssue, @pair = @ArmTable, @lo = @lo, @hi = @hi;

        -- ---- column-level differences on key-matched rows ----------------------
        IF @valueList IS NOT NULL
        BEGIN
            SET @sql = N'
INSERT #Result (TablePair, Issue, KeyValues, ColumnName, ArmValue, DboValue)
SELECT TOP (@cap) @pair, ''VALUE_DIFF'', ' + @KeyExprA + N', v.ColumnName, v.ArmValue, v.DboValue
FROM arm.' + QUOTENAME(@ArmTable) + N' a
JOIN dbo.' + QUOTENAME(@DboTable) + N' d ON ' + @KeyJoin + N'
CROSS APPLY (VALUES
' + @valueList + N'
) v (ColumnName, ArmValue, DboValue, IsDiff)
WHERE v.IsDiff = 1 AND ' + @armFilter + N';';

            EXEC sp_executesql @sql,
                 N'@cap INT, @pair SYSNAME, @lo DATE, @hi DATE',
                 @cap = @MaxRowsPerIssue, @pair = @ArmTable, @lo = @lo, @hi = @hi;
        END

        -- ---- per-pair summary --------------------------------------------------
        SET @sql = N'SELECT @aOut = COUNT_BIG(1) FROM arm.' + QUOTENAME(@ArmTable) + N' a WHERE ' + @armFilter + N';';
        EXEC sp_executesql @sql, N'@aOut INT OUTPUT, @lo DATE, @hi DATE', @aOut = @armRows OUTPUT, @lo = @lo, @hi = @hi;
        SET @sql = N'SELECT @dOut = COUNT_BIG(1) FROM dbo.' + QUOTENAME(@DboTable) + N' d WHERE ' + @dboFilter + N';';
        EXEC sp_executesql @sql, N'@dOut INT OUTPUT, @lo DATE, @hi DATE', @dOut = @dboRows OUTPUT, @lo = @lo, @hi = @hi;

        INSERT #Result (TablePair, Issue, KeyValues, ColumnName, ArmValue, DboValue)
        SELECT @ArmTable, 'SUMMARY',
               CASE WHEN @DateCol IS NULL THEN N'(no date column - full compare)'
                    ELSE CONCAT(@DateCol, N' ', CONVERT(NVARCHAR(10), @lo, 23), N'..', CONVERT(NVARCHAR(10), @hi, 23)) END,
               N'dbo.' + @DboTable,
               CONCAT(@armRows, N' arm row(s)'), CONCAT(@dboRows, N' dbo row(s)');

        FETCH NEXT FROM pair_cur INTO @ArmTable, @DboTable, @KeyJoin, @KeyExprA, @KeyExprD, @DateCol;
    END

    CLOSE pair_cur;
    DEALLOCATE pair_cur;

    SELECT TablePair, Issue, KeyValues, ColumnName, ArmValue, DboValue
    FROM #Result
    ORDER BY TablePair, CASE Issue WHEN 'SUMMARY' THEN 0 ELSE 1 END, Issue, Seq;
END
GO

